export const TRACKING_TYPES = {
  event: {
    kitesurferClick: "Click to kitesurfer page",
    developerClick: "Click to developer page",
    logoClick: "Click to CA logo",
    darkThemeClick: "Set dark theme",
    lightThemeClick: "Set light theme",
    esLanguageClick: "Set Spanish language",
    enLanguageClick: "Set English language",
    downloadCV: "Download CV",
    visitProjectClick: "Click to visit project",
    githubProjectClick: "Click to project GitHub",
    youtubeIconClick: "Click on YouTube",
    kiteJumpsOrderClick: "Change kite jumps order",
    editCV: "Start to Edit CV",
    saveCV: "Finish to Edit CV",
    buyMeACoffee: "Click toBuy me a coffee",
  },
  page: {
    home: "Home",
    about: "About",
    contact: "Contact",
    kitesurfer: "Kitesurfer",
    developer: "Developer",
    privacyPolicy: "Privacy Policy",
    legalNotice: "Legal Notice",
  },
};
